services:
  fpm:
    build: ./
    volumes:
      - ./src:/var/www
    networks:
      - laravel_app
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 8020:80
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel_app
  db:
    image: mysql:9.2.0
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: "laravel"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "laravel"
      MYSQL_DATABASE: "laravel"
    networks:
      - laravel_app
networks:
  laravel_app:
